import { AIScanResult, CircularCenter, Listing, Profile, Activity } from '@/types';

export interface SeedDemoItem extends AIScanResult {
  id: string;
  image_url: string;
}

export const SEED_DEMO_ITEMS: SeedDemoItem[] = [
  {
    id: 'demo-1',
    item_name: 'Clear PET Plastic Water Bottle',
    category: 'Plastic',
    material: 'Polyethylene Terephthalate (PET #1)',
    condition: 'Used - Intact',
    reusable: true,
    repairable: false,
    recyclable: true,
    recommended_action: 'Recycle',
    circularity_score: 78,
    confidence: 96,
    reason: 'PET Plastic #1 is widely accepted by local curbside recycling programs. Can be recycled into synthetic fibers and fleece.',
    co2_estimate: 0.12,
    image_url: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'demo-2',
    item_name: 'Vintage Smartphone (Cracked Screen)',
    category: 'Electronics',
    material: 'Lithium-Ion, Aluminum, Glass, Copper',
    condition: 'Damaged Screen - Functional Board',
    reusable: false,
    repairable: true,
    recyclable: true,
    recommended_action: 'Repair',
    circularity_score: 82,
    confidence: 92,
    reason: 'Screen replacement can restore 100% utility. If unfixable, high-value precious metals inside warrant certified e-waste recycling.',
    co2_estimate: 15.4,
    image_url: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'demo-3',
    item_name: 'Solid Wood Dining Study Chair',
    category: 'Furniture',
    material: 'Oak Wood & Non-toxic Finish',
    condition: 'Worn Surface - Structurally Sound',
    reusable: true,
    repairable: true,
    recyclable: false,
    recommended_action: 'Repair',
    circularity_score: 87,
    confidence: 94,
    reason: 'This wooden chair appears structurally intact with minor surface wear. Sanding and refinishing will extend its life by decades.',
    co2_estimate: 32.5,
    image_url: 'https://images.unsplash.com/photo-1503602642458-232111445657?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'demo-4',
    item_name: 'Denim Jeans (Slight Knee Fray)',
    category: 'Textile',
    material: '100% Organic Cotton Denim',
    condition: 'Good - Light Wear',
    reusable: true,
    repairable: true,
    recyclable: true,
    recommended_action: 'Reuse',
    circularity_score: 91,
    confidence: 95,
    reason: 'Cotton denim in good condition has high marketplace value. Reusing avoids consuming 7,500 liters of fresh water required for new pair.',
    co2_estimate: 8.6,
    image_url: 'https://images.unsplash.com/photo-1542272604-780c96856592?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'demo-5',
    item_name: 'Corrugated Shipping Cardboard Box',
    category: 'Paper',
    material: 'Unbleached Kraft Cellulose Fiber',
    condition: 'Flattened - Clean',
    reusable: true,
    repairable: false,
    recyclable: true,
    recommended_action: 'Recycle',
    circularity_score: 85,
    confidence: 98,
    reason: 'Clean corrugated cardboard fiber can be re-pulped up to 7 times. Reusing for shipping saves energy and landfill volume.',
    co2_estimate: 0.45,
    image_url: 'https://images.unsplash.com/photo-1589939705384-5185137a7f0f?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'demo-6',
    item_name: 'Amber Glass Bottle with Cap',
    category: 'Glass',
    material: 'Soda-Lime Silica Glass',
    condition: 'Like New - Intact',
    reusable: true,
    repairable: false,
    recyclable: true,
    recommended_action: 'Reuse',
    circularity_score: 94,
    confidence: 97,
    reason: 'Glass is 100% infinitely recyclable without quality loss. Sanitizing for refill saves 30% process heat vs raw melting.',
    co2_estimate: 0.35,
    image_url: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'demo-7',
    item_name: 'Aluminum Beverage Can',
    category: 'Metal',
    material: '99% Pure Aluminum Alloy',
    condition: 'Used - Empty',
    reusable: false,
    repairable: false,
    recyclable: true,
    recommended_action: 'Recycle',
    circularity_score: 96,
    confidence: 99,
    reason: 'Recycling aluminum saves 95% of the energy required to extract bauxite ore. Aluminum can return to shelf as new can in 60 days.',
    co2_estimate: 0.28,
    image_url: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'demo-8',
    item_name: 'Ultrabook Laptop (Slight Battery Wear)',
    category: 'Electronics',
    material: 'Magnesium Alloy, Silicon, Li-Polymer',
    condition: 'Working - Needs Battery',
    reusable: true,
    repairable: true,
    recyclable: true,
    recommended_action: 'Resell',
    circularity_score: 89,
    confidence: 91,
    reason: 'High processing specs remain fast. Battery swap cost is small relative to $600+ replacement cost of buying new.',
    co2_estimate: 180.0,
    image_url: 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'demo-9',
    item_name: 'Hardcover Fiction Novel Collection',
    category: 'Paper',
    material: 'FSC-Certified Acid-Free Paper',
    condition: 'Excellent - Clean Spine',
    reusable: true,
    repairable: false,
    recyclable: true,
    recommended_action: 'Donate',
    circularity_score: 95,
    confidence: 98,
    reason: 'Physical books preserve knowledge cleanly for decades. Donating to community library maximizes social and literacy impact.',
    co2_estimate: 2.8,
    image_url: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'demo-10',
    item_name: 'Compact Espresso Coffee Machine',
    category: 'Furniture',
    material: 'Stainless Steel & ABS Thermoplastic',
    condition: 'Needs Descaling - Motor Works',
    reusable: true,
    repairable: true,
    recyclable: false,
    recommended_action: 'Repair',
    circularity_score: 84,
    confidence: 89,
    reason: 'Descaling heater element restores full pressure. Appliance housing and pump are built for long operational durability.',
    co2_estimate: 24.0,
    image_url: 'https://images.unsplash.com/photo-1517668808822-9e428824603b?auto=format&fit=crop&w=600&q=80',
  }
];

export const SEED_DEMO_CENTERS: CircularCenter[] = [
  {
    id: 'center-1',
    name: 'EcoTech E-Waste & Electronics Recycling Center',
    type: 'E-waste',
    address: '742 Evergreen Terrace, Eco District',
    latitude: 37.774929,
    longitude: -122.419416,
    accepted_materials: ['Electronics', 'Metal', 'Batteries'],
    phone: '+1 (555) 234-5678',
    distance_km: 1.2,
    hours: 'Mon - Sat: 8:00 AM - 6:00 PM',
    website: 'https://ecotech-recycle.org',
  },
  {
    id: 'center-2',
    name: 'GreenThread Clothing & Textile Donation Hub',
    type: 'Donation',
    address: '108 Compassion Way, Metro City',
    latitude: 37.783333,
    longitude: -122.416667,
    accepted_materials: ['Textile', 'Leather', 'Shoes', 'Paper'],
    phone: '+1 (555) 876-5432',
    distance_km: 2.4,
    hours: 'Daily: 9:00 AM - 7:00 PM',
    website: 'https://greenthread.org',
  },
  {
    id: 'center-3',
    name: 'FixIt All Community Repair Cafe',
    type: 'Repair',
    address: '45 Renewal Blvd, Tech Park',
    latitude: 37.765000,
    longitude: -122.425000,
    accepted_materials: ['Furniture', 'Electronics', 'Metal', 'Textile'],
    phone: '+1 (555) 345-6789',
    distance_km: 3.1,
    hours: 'Tue - Sun: 10:00 AM - 5:00 PM',
    website: 'https://fixitcafe.org',
  },
  {
    id: 'center-4',
    name: 'ClearStream Glass, Paper & Metal Recovery',
    type: 'Recycling',
    address: '89 Industrial Parkway, Dockside',
    latitude: 37.755000,
    longitude: -122.405000,
    accepted_materials: ['Glass', 'Metal', 'Plastic', 'Paper'],
    phone: '+1 (555) 901-2345',
    distance_km: 4.5,
    hours: 'Mon - Fri: 7:00 AM - 5:00 PM',
    website: 'https://clearstream-recovery.com',
  },
  {
    id: 'center-5',
    name: 'Second Life Furniture & Home Thrift Drop-off',
    type: 'Donation',
    address: '312 Goodwill St, Midtown',
    latitude: 37.790000,
    longitude: -122.410000,
    accepted_materials: ['Furniture', 'Organic', 'Mixed', 'Textile'],
    phone: '+1 (555) 432-1098',
    distance_km: 5.2,
    hours: 'Mon - Sat: 9:30 AM - 6:00 PM',
    website: 'https://secondlife-thrift.org',
  },
  {
    id: 'center-6',
    name: 'Metro Bio-Compost & Organic Waste Facility',
    type: 'Recycling',
    address: '500 Green Earth Lane, Valley View',
    latitude: 37.740000,
    longitude: -122.430000,
    accepted_materials: ['Organic', 'Paper', 'Mixed'],
    phone: '+1 (555) 654-3210',
    distance_km: 6.8,
    hours: 'Mon - Fri: 8:00 AM - 4:00 PM',
    website: 'https://metrocompost.gov',
  }
];

export const SEED_DEMO_LISTINGS: Listing[] = [
  {
    id: 'listing-1',
    user_id: 'user-demo-1',
    title: 'Solid Oak Dining Study Chair - Refinished',
    description: 'Beautiful oak chair in great condition. Sanded and sealed with organic oil finish. Free to good home!',
    category: 'Furniture',
    condition: 'Refurbished',
    price: 0,
    image_url: 'https://images.unsplash.com/photo-1503602642458-232111445657?auto=format&fit=crop&w=600&q=80',
    location: 'North Bay / Downtown',
    status: 'available',
    created_at: new Date(Date.now() - 3600000 * 5).toISOString(),
    user_profile: {
      full_name: 'Elena Rostova',
      avatar_url: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=150&q=80',
    }
  },
  {
    id: 'listing-2',
    user_id: 'user-demo-2',
    title: 'Vintage Leather Jacket (Unisex M)',
    description: 'Genuine dark brown leather jacket. Slight vintage patina, zippers smooth and fully operational.',
    category: 'Textile',
    condition: 'Good',
    price: 25,
    image_url: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=600&q=80',
    location: 'Westside Heights',
    status: 'available',
    created_at: new Date(Date.now() - 3600000 * 18).toISOString(),
    user_profile: {
      full_name: 'Marcus Vance',
      avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80',
    }
  },
  {
    id: 'listing-3',
    user_id: 'user-demo-3',
    title: 'Working Espresso Coffee Maker',
    description: 'Cleaned and descaled espresso machine. Comes with 2 portafilters and stainless steel tamper.',
    category: 'Electronics',
    condition: 'Very Good',
    price: 35,
    image_url: 'https://images.unsplash.com/photo-1517668808822-9e428824603b?auto=format&fit=crop&w=600&q=80',
    location: 'Central District',
    status: 'available',
    created_at: new Date(Date.now() - 3600000 * 26).toISOString(),
    user_profile: {
      full_name: 'Sophia Chen',
      avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&q=80',
    }
  }
];

export const DEMO_USER_PROFILE: Profile = {
  id: 'usr-demo-100',
  full_name: 'Pratham Sharma',
  email: 'pratham.eco@example.com',
  avatar_url: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=150&q=80',
  eco_points: 430,
  co2_saved: 68.4,
  items_diverted: 6,
  items_reused: 3,
  items_recycled: 2,
  items_donated: 1,
  created_at: '2026-09-01T10:00:00.000Z',
};

export const SEED_ACTIVITIES: Activity[] = [
  {
    id: 'act-1',
    user_id: DEMO_USER_PROFILE.id,
    activity_type: 'Repair',
    item_name: 'Solid Wood Dining Chair',
    points: 150,
    co2_saved: 32.5,
    created_at: new Date(Date.now() - 3600000 * 12).toISOString(),
  },
  {
    id: 'act-2',
    user_id: DEMO_USER_PROFILE.id,
    activity_type: 'Reuse',
    item_name: 'Denim Jeans (Given to Neighbor)',
    points: 120,
    co2_saved: 8.6,
    created_at: new Date(Date.now() - 3600000 * 48).toISOString(),
  },
  {
    id: 'act-3',
    user_id: DEMO_USER_PROFILE.id,
    activity_type: 'Donate',
    item_name: 'Hardcover Fiction Books',
    points: 110,
    co2_saved: 2.8,
    created_at: new Date(Date.now() - 3600000 * 72).toISOString(),
  },
  {
    id: 'act-4',
    user_id: DEMO_USER_PROFILE.id,
    activity_type: 'Recycle',
    item_name: 'Clear PET Water Bottle & Cans',
    points: 75,
    co2_saved: 0.4,
    created_at: new Date(Date.now() - 3600000 * 96).toISOString(),
  }
];

export const SEED_LEADERBOARD: Profile[] = [
  DEMO_USER_PROFILE,
  {
    id: 'usr-demo-2',
    full_name: 'Elena Rostova',
    email: 'elena@example.com',
    avatar_url: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=150&q=80',
    eco_points: 390,
    co2_saved: 52.1,
    items_diverted: 5,
    items_reused: 2,
    items_recycled: 2,
    items_donated: 1,
    created_at: '2026-09-02T10:00:00.000Z',
  },
  {
    id: 'usr-demo-3',
    full_name: 'Marcus Vance',
    email: 'marcus@example.com',
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80',
    eco_points: 340,
    co2_saved: 41.8,
    items_diverted: 4,
    items_reused: 1,
    items_recycled: 2,
    items_donated: 1,
    created_at: '2026-09-03T10:00:00.000Z',
  },
  {
    id: 'usr-demo-4',
    full_name: 'Sophia Chen',
    email: 'sophia@example.com',
    avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&q=80',
    eco_points: 295,
    co2_saved: 38.0,
    items_diverted: 4,
    items_reused: 2,
    items_recycled: 1,
    items_donated: 1,
    created_at: '2026-09-04T10:00:00.000Z',
  }
];

export const SEED_CENTERS = SEED_DEMO_CENTERS;
export const SEED_LISTINGS = SEED_DEMO_LISTINGS;
